[backend]
precision = double
rank-allocator = linear

[backend-cuda]
device-id = local-rank
mpi-type = standard

[backend-openmp]
;cblas-st = Enter path to local single-threaded BLAS library for OpenMP backend
;cblas-mt = Enter path to local multi-threaded BLAS library for OpenMP backend

[constants]
gamma = 1.4
mu = 0.0000037
Pr = 0.72

M = 0.1
uc = 1.0
rhoc = 1.0

[solver]
system = navier-stokes
order = 3
shock-capturing = entropy-filter

[solver-entropy-filter]
d-min = 1e-6
p-min = 1e-6
niters = 20
formulation = rho_p

[solver-ec-artificial-viscosity]
enabled = true

[solver-time-integrator]
scheme = rk45
controller = pi
tstart = 0.0
tend = 500.0
dt = 2.5e-8
atol = 1e-6
rtol = 1e-6

[solver-interfaces]
riemann-solver = rusanov
ldg-beta = 0.5
ldg-tau = 0.0

[solver-interfaces-quad]
flux-pts = gauss-legendre-lobatto

[solver-elements-hex]
soln-pts = gauss-legendre-lobatto

[soln-bcs-wall]
type = no-slp-adia-wall

[soln-bcs-inflow]
type = char-riem-inv
rho = rhoc
u = uc
v = 0
w = 0
p = rhoc*uc*uc/(M*M*gamma)

[soln-bcs-outflow]
type = char-riem-inv
p = rhoc*uc*uc/(M*M*gamma)
u = uc
v = 0
w = 0
rho = rhoc

[soln-ics]
rho = rhoc
u = uc
v = 0
w = 0
p = rhoc*uc*uc/(M*M*gamma)

[soln-plugin-nancheck]
nsteps = 200

[soln-plugin-writer]
dt-out = 50.0
basedir = .
basename = naca-ecav-{t:.2f}
